# Generated by Django 4.1 on 2022-08-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
