# Generated by Django 4.1 on 2022-08-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_email_adress_venue_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='plant_inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant_name', models.CharField(max_length=120, verbose_name='Plant Name')),
                ('color', models.CharField(max_length=20)),
                ('Plant_type', models.CharField(blank=True, max_length=10, verbose_name='Plant_type')),
                ('Origin', models.CharField(blank=True, max_length=100, verbose_name='Origin')),
            ],
        ),
    ]
